//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Information
    {
        public int ContactID { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string comment { get; set; }
    }
}
